version: '3'
services:
  mysqldb:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  order-service:
    build: ./order-service/
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
