version: '3'
services:
  mysqldb:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    - MONGO_INITDB_DATABASE=development
    - MONGO_INITDB_USER=mongodb
    - MONGO_INITDB_PWD=mongodb
    ports:
      - '27017:27017'
    volumes:
      - /home/serhii/database/initdb.d:/docker-entrypoint-initdb.d/

  order-service:
    build: ./order-service/
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
