version: '3'
services:
  mysqldb:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on: mysqldb
